<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="3082" started-at="2019-03-29T09:03:46Z" finished-at="2019-03-29T09:03:49Z">
    <groups>
    </groups>
    <test name="Create and Rename Test positive scenario" duration-ms="3082" started-at="2019-03-29T09:03:46Z" finished-at="2019-03-29T09:03:49Z">
      <class name="Scenario1Test">
        <test-method status="FAIL" signature="CreateAndRenameTest(java.lang.String, java.lang.String)[pri:0, instance:Scenario1Test@e4d37f]" name="CreateAndRenameTest" duration-ms="3051" started-at="2019-03-29T09:03:46Z" finished-at="2019-03-29T09:03:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[sample38]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sample39]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[please check the channel name]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: please check the channel name
at org.testng.Assert.fail(Assert.java:96)
at Scenario1Test.CreateAndRenameTest(Scenario1Test.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateAndRenameTest -->
      </class> <!-- Scenario1Test -->
    </test> <!-- Create and Rename Test positive scenario -->
  </suite> <!-- Suite -->
</testng-results>
